run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - gosec
    - unconvert
    - unparam
    - nakedret
    - prealloc
    - copyloopvar
    - nilerr
    - nolintlint

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - fieldalignment

  gofmt:
    simplify: true

  revive:
    rules:
      - name: var-naming
        severity: warning
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: indent-error-flow
      - name: empty-block
      - name: superfluous-else
      - name: unreachable-code
      - name: unused-parameter

  gosec:
    excludes:
      - G204 # Subprocess launched with variable - we need this for ctr/docker commands
      - G304 # File path provided as taint input - we need this for reading files

  misspell:
    locale: US

  nakedret:
    max-func-lines: 30

  unparam:
    check-exported: false

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - errcheck

    # Exclude known issues
    - linters:
        - staticcheck
      text: "SA1019:" # Ignore deprecation warnings for now

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
