# Dockerfile

# Use the official Ubuntu 20.04 as the base image
FROM ubuntu:24.04

# Prevent interactive prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

# Install dependencies and skopeo from official repositories
RUN apt-get update && \
    apt-get install -y \
      bash \
      curl \
      jq \
      git \
      ca-certificates \
      gnupg2 \
      software-properties-common && \
    add-apt-repository universe && \
    apt-get update && \
    apt-get install -y skopeo docker.io && \
    rm -rf /var/lib/apt/lists/*

# Install kubectl
RUN VERSION=$(curl -L -s https://dl.k8s.io/release/stable.txt) && \
    curl -LO "https://dl.k8s.io/release/${VERSION}/bin/linux/amd64/kubectl" && \
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

# Install crictl (optional, if you still need it)
RUN VERSION="v1.24.0" && \
    curl -LO https://github.com/kubernetes-sigs/cri-tools/releases/download/${VERSION}/crictl-${VERSION}-linux-amd64.tar.gz && \
    tar -zxvf crictl-${VERSION}-linux-amd64.tar.gz -C /usr/local/bin && \
    chmod +x /usr/local/bin/crictl && \
    rm crictl-${VERSION}-linux-amd64.tar.gz

# Set entrypoint
ENTRYPOINT ["/bin/bash"]
