# values.yaml

# Container Registry Configuration
registry:
  url: "your-registry-url.com"            # Replace with your registry URL
  username: "your-username"               # Replace with your registry username
  password: "your-password"               # Replace with your registry password
  email: "your-email@example.com"         # Replace with your email

# Namespaces and Deployments to Monitor
monitor:
  namespaces:
    - "default"
    - "kube-system"
  deployments: []  # If empty, all deployments in the specified namespaces will be monitored
  # Example:
  # deployments:
  #   - "deployment1"
  #   - "deployment2"

# Image Settings
image:
  repository: "bash"
  tag: "latest"
  pullPolicy: "IfNotPresent"

# DaemonSet Settings
daemonset:
  name: "push-missed-images"
  namespace: "kube-system"

# RBAC Configuration
rbac:
  create: true
