name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Please fill in as much information as possible.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of the bug
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Deploy helm chart with...
        2. Create deployment with image...
        3. Check logs...
        4. See error
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the tool are you running?
      placeholder: v2.3.0
    validations:
      required: true

  - type: dropdown
    id: runtime
    attributes:
      label: Container Runtime
      description: Which container runtime are you using?
      options:
        - containerd
        - Docker
        - Not sure
    validations:
      required: true

  - type: dropdown
    id: k8s-distro
    attributes:
      label: Kubernetes Distribution
      description: Which Kubernetes distribution?
      options:
        - Standard (kubeadm, kops, etc)
        - k3s
        - k0s
        - microk8s
        - GKE
        - EKS
        - AKS
        - Other
    validations:
      required: true

  - type: input
    id: k8s-version
    attributes:
      label: Kubernetes Version
      description: What version of Kubernetes? (kubectl version --short)
      placeholder: v1.28.0
    validations:
      required: true

  - type: dropdown
    id: registry
    attributes:
      label: Registry Type
      description: Which container registry are you using?
      options:
        - Docker Hub
        - Harbor
        - Nexus
        - GitLab Container Registry
        - GitHub Container Registry (ghcr.io)
        - AWS ECR
        - Google Artifact Registry
        - Azure Container Registry
        - Other
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: Please copy and paste any relevant log output
      render: shell
      placeholder: |
        kubectl logs -n kube-system -l app=push-missed-images --tail=50

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Your values.yaml or relevant configuration (remove secrets!)
      render: yaml
      placeholder: |
        registry:
          url: harbor.example.com
        monitor:
          namespaces:
            - production

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true
        - label: I have included all relevant information above
          required: true
        - label: I have removed any sensitive information (passwords, tokens, etc)
          required: true
