# templates/secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: {{ .Values.daemonset.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}" .Values.registry.url .Values.registry.username .Values.registry.password .Values.registry.email (printf "%s:%s" .Values.registry.username .Values.registry.password | b64enc) | b64enc }}
